body:
  application/x-www-form-urlencoded:
    formParameters:
      since:
        description: |
          The start of the date range over which you want to search.
          The time element is optional.
        required: true
      until:
        description: |
          The end of the date range over which you want to search.
          This should be in the same format as since.
          The size of the date range must be less than 3 months.
        required: true