#%Validation Profile 1.0

profile: Test Profile

description: Test profile that ignores validations about schemes


info:
  - my-custom-validation


validations:

  my-custom-validation:
    message: Resource relative path must start with 'MyResource' !!!
    targetClass: http.EndPoint
    propertyConstraints:
      http.path:
        pattern: ^/MyResource.*$
