type: x-token-schema
description: Schema which requires Application ID and REST API Key
describedBy:
  headers:
    Authorization:
      required: true
      example: 'Token token=E7px6VVr3PVHZPJq51oa'